/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.edgger.alfabattle.task1.model.openapi;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AvailableNow
 */
@JsonPropertyOrder({
        AvailableNow.JSON_PROPERTY_CASH_IN,
        AvailableNow.JSON_PROPERTY_CASH_OUT,
        AvailableNow.JSON_PROPERTY_ONLINE,
        AvailableNow.JSON_PROPERTY_PAYMENTS
})
@Data
@AllArgsConstructor
@NoArgsConstructor
public class AvailableNow {
    public static final String JSON_PROPERTY_CASH_IN = "cashIn";
    private String cashIn;

    public static final String JSON_PROPERTY_CASH_OUT = "cashOut";
    private String cashOut;

    public static final String JSON_PROPERTY_ONLINE = "online";
    private String online;

    public static final String JSON_PROPERTY_PAYMENTS = "payments";
    private String payments;

}

