/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.edgger.alfabattle.task1.model.openapi;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * BankATMStatus
 */
@JsonPropertyOrder({
        BankATMStatus.JSON_PROPERTY_ATMS,
        BankATMStatus.JSON_PROPERTY_BANK_LICENSE
})
@Data
@AllArgsConstructor
@NoArgsConstructor
public class BankATMStatus {
    public static final String JSON_PROPERTY_ATMS = "atms";
    private List<ATMStatus> atms = null;

    public static final String JSON_PROPERTY_BANK_LICENSE = "bankLicense";
    private String bankLicense;

}

