/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.edgger.alfabattle.task1.model.openapi;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Coordinates
 */
@JsonPropertyOrder({
        Coordinates.JSON_PROPERTY_LATITUDE,
        Coordinates.JSON_PROPERTY_LONGITUDE
})
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Coordinates {
    public static final String JSON_PROPERTY_LATITUDE = "latitude";
    private Double latitude;

    public static final String JSON_PROPERTY_LONGITUDE = "longitude";
    private Double longitude;

}

