/*
 * Сервис проверки статуса банкоматов
 * Сервис, возвращающий информацию о банкоматах Альфа-Банка
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apisupport@alfabank.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.edgger.alfabattle.task1.model.openapi;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * SupportInfo
 */
@JsonPropertyOrder({
        SupportInfo.JSON_PROPERTY_EMAIL,
        SupportInfo.JSON_PROPERTY_OTHER,
        SupportInfo.JSON_PROPERTY_PHONE
})
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SupportInfo {
    public static final String JSON_PROPERTY_EMAIL = "email";
    private String email;

    public static final String JSON_PROPERTY_OTHER = "other";
    private String other;

    public static final String JSON_PROPERTY_PHONE = "phone";
    private String phone;

}

